image:
    - Visual Studio 2017

environment:
    matrix:
        - TASK: lab0

install:
    - cmd: choco install chocolatey-core.extension --ignore-dependencies
    - cmd: choco install ninja --ignore-dependencies
    - cmd: choco install cmake --ignore-dependencies
    - cmd: choco install cppcheck --ignore-dependencies
    - cmd: set PATH=%PATH%;C:\Program Files\Cppcheck

before_build:
    - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" amd64

build_script:
    - mkdir build
    - cd build
    - cmake ../%TASK% -GNinja -DCMAKE_C_COMPILER=clang-cl
    - cmake --build .
    - cmake --target test
